apiVersion: v1
kind: Service
metadata:
  name: add-format-app-microservice
spec:
  selector:
    app: add-format-app
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: add-format-app
spec:
  selector:
    matchLabels:
      app: add-format-app
  template:
    metadata:
      labels:
        app: add-format-app
    spec:
      containers:
        - name: add-format-microservice
          image: docker.io/azure92/add-format-microservice
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080